version: "3.4"

networks:
  frontend: 
  backend: 

### 这里定义了mysql所用到的数据卷
volumes:
  mysql-data:


services:
  mysql:
    container_name: mysql_service
    build: ./mysql
    ports:
      - "33060:3306"  
    networks:
      - backend
    restart: on-failure:3

    volumes:
      - mysql-data:/var/lib/mysql ### 数据卷，mysql数据就存放在这里
      - ./mysql/logs:/logs
  
  redis:
    container_name: redis_service
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - backend

  php:
    expose:
      - "9000"
    container_name: php_service
    build: ./php
    volumes:
      - /Users/caicheng/code/php/laravel_init:/var/www/laravel_init
    networks:
      - frontend
      - backend
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis

  nginx:
    container_name: nginx_service
    build: ./nginx
    ports:
      - "8081:80"
    volumes:
      - /Users/caicheng/code/php/laravel_init:/var/www/laravel_init
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
    networks:
      - frontend
    depends_on:
      - php


